wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725382663
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
